version: '2'
services:

  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: mongo
    ports:
      - '27017:27017'

  app:
    container_name: app
    build:
      dockerfile: Dockerfile.prod
      context: .
    volumes:
      - ./:/go/src/whatbugsme
    ports:
      - '8888:8888'
    environment:
      - SERVER=mongo