FROM golang:latest as builder

COPY . /go/src/whatbugsme
WORKDIR /go/src/whatbugsme

RUN touch server.log

RUN go get ./...
RUN go install ./...

CMD go get github.com/pilu/fresh && fresh;

EXPOSE 8888