version: '2'
services:

  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: mongo
    user: ${USER} # production line - avoid locally
    ports:
      - '27017:27017'
    volumes:
      - './data:/bitnami'        

  app:
    container_name: app
    build:
      dockerfile: Dockerfile.prod # locally use .dev
      context: .
    volumes:
      - ./:/go/src/whatbugsme
    ports:
      - '8888:8888'
    environment:
      - SERVER=mongo